### ISSUE TITLE
Actividad 4 mapa mental

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Diegocruz040708#1]
[Actividad 4 Mapa Mental Diego Cruz Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Diegocruz040708/files/9603954/Actividad.4.Mapa.Mental.Diego.Cruz.Cruz.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 4
Obtuviste un 19.2% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
